apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka1
    app : suplier-portal
  name: kafka1
  #namespace : supplier-portal-ns
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
  selector:
    service: kafka1
status:
  loadBalancer: {}