apiVersion: v1
kind: Service
metadata:
  labels:
    service: zoo1
    app: supplier-portal
  name: zoo1
  namespace: supplier-portal-ns
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    service: zoo1
status:
  loadBalancer: {}